### ISSUE TITLE
Favourites list shouldn't be editable

### ISSUE THREAD

**Issue by eoinnoble** [creativecommons/open-ledger#101]
The 'Favourites' list probably shouldn’t be editable, since you can’t really edit it – if you change its name to something else and favourite another photo a new 'Favourites' list will appear on the lists screen.

**Comment by lizadaly** [comment]
I wasn't sure how to implement this: as a fake list that just shows what you have Favorited and is otherwise immutable, or (what I did) a real list that listens to 'add favorite' events but is otherwise independent. Obviously you expected the former behavior so I'll swap the implementation (it's easier anyway).

**Comment by lizadaly** [comment]
Folding this into #97
