### ISSUE TITLE
Security vulnerability with hoek (jsdom dependency)

### ISSUE THREAD

**Issue by pa-w** [creativecommons/open-ledger#236]
Github detected a vulnerable dependency in our code. 

![b230b59e-ed37-42ce-879b-f80132b60589](https://user-images.githubusercontent.com/7355017/39708463-477c7eec-51e5-11e8-80e5-bbc681a090ff.jpeg)

**Comment by aldenstpage** [comment]
This is from our dependency on jsdom. The dependency graph is jsdom->request->hawk->vulnerable version of hoek.

In package.json, you can see that this is **only a dependency in our development environment**:
```
  "devDependencies": {
    . . .
    "chai": "^3.5.0",
    "jsdom": "9.8.3",
    "jsdom-global": "2.1.0",
    "mocha": "^3.5.0",
    . . .
```
Since this does not affect the production environment, this is **a low priority fix** for us. I think it will be possible to make it go away by generating a fresh package-lock. We may be stuck if `request` hasn't been updated with a fix.

**Comment by aldenstpage** [comment]
The maintainer of jsdom has [declined to take action](https://github.com/jsdom/jsdom/issues/2163).

**Comment by aldenstpage** [comment]
Closed since we are no longer using the original open-ledger app
